"""
Remediation Engine - v1 Schema + Stub

CRITICAL CONSTRAINTS:
- Does NOT auto-detect gaps from handwriting
- Only uses gaps already returned by Agent/verifier
- If fields don't exist -> return no_remediation
- Items from existing problem bank only
- mini_lesson content: "Generated by tutor agent at runtime" (placeholder)

V1 Scope:
- Schema definition for remediation items
- Stub implementation that requires pre-detected gaps
- Basic problem matching by concept

Future V2:
- Auto-detect prerequisite gaps from error patterns
- Integration with vision analysis
- Adaptive mini-lesson generation
"""

from typing import Optional
import logging

logger = logging.getLogger(__name__)


def get_remediation_items(
    detected_gap: Optional[str],
    prerequisite_concepts: Optional[list],
    original_problem_id: str,
    course: str,
) -> dict:
    """
    Return remediation items if gap was already detected by Agent.
    Returns no_remediation if no gap detected.

    Args:
        detected_gap: Gap detected by agent/verifier (e.g., "chain_rule")
        prerequisite_concepts: List of prerequisite concepts needed
        original_problem_id: ID of the problem student struggled with
        course: Course code (e.g., "126")

    Returns:
        Dict with remediation plan or has_remediation=False
    """
    # v1: Only proceed if gap already detected externally
    if not detected_gap and not prerequisite_concepts:
        return {"has_remediation": False}

    # Import here to avoid circular imports
    from problem_loader import load_problems

    gap_concepts = prerequisite_concepts or [detected_gap]

    # Load problems for the course
    try:
        all_problems = load_problems(course)
    except Exception as e:
        logger.error(f"Failed to load problems for remediation: {e}")
        return {"has_remediation": False}

    # Find basic/easy problems matching gap concepts
    basic_problems = [
        p for p in all_problems
        if _is_remediation_candidate(p, gap_concepts)
    ]

    # Build remediation items
    items = []

    # Add mini_lesson placeholder (content generated at runtime by agent)
    items.append({
        "type": "mini_lesson",
        "subtopic": detected_gap or gap_concepts[0],
        "content": "Generated by tutor agent at runtime",  # Placeholder
        "display_name": _format_concept_name(detected_gap or gap_concepts[0]),
    })

    # Add basic problem if found
    if basic_problems:
        p = basic_problems[0]
        stem = getattr(p, "stem", None) or ""
        if len(stem) > 60:
            title = stem[:60] + "..."
        elif stem:
            title = stem
        else:
            title = getattr(p, "id", "Practice Problem")

        items.append({
            "type": "basic_problem",
            "problem_id": getattr(p, "id", ""),
            "title": title,
            "source": getattr(p, "exam", ""),
            "reason": f"Practice the prerequisite: {_format_concept_name(gap_concepts[0])}",
        })

    # Add retry original problem
    items.append({
        "type": "retry",
        "problem_id": original_problem_id,
        "reason": "Try the original problem again with fresh understanding",
    })

    return {
        "has_remediation": True,
        "title": "Quick fix before continuing",
        "gap_description": f"Let's strengthen: {_format_concept_name(detected_gap or gap_concepts[0])}",
        "items": items,
    }


def _is_remediation_candidate(problem, gap_concepts: list) -> bool:
    """
    Check if problem is a good remediation candidate.

    Criteria:
    - Matches gap concepts
    - Prefer easy difficulty
    - Has solution if possible
    """
    # Must match at least one gap concept
    problem_concepts = getattr(problem, "concepts", [])
    problem_topic = getattr(problem, "topic", "")

    has_match = False
    for gap in gap_concepts:
        if gap in problem_concepts or gap == problem_topic:
            has_match = True
            break

    if not has_match:
        return False

    # Prefer easy problems
    difficulty = getattr(problem, "difficulty", None)
    if difficulty and difficulty not in ["easy", "medium"]:
        return False

    return True


def _format_concept_name(concept: str) -> str:
    """
    Format concept key to human-readable name.

    Examples:
        "chain_rule" -> "Chain Rule"
        "double_integrals" -> "Double Integrals"
    """
    if not concept:
        return "Unknown Concept"
    return concept.replace("_", " ").title()


# =============================================================================
# Schema Definitions for Future Use
# =============================================================================

REMEDIATION_ITEM_TYPES = {
    "mini_lesson": {
        "description": "Brief concept review generated by agent",
        "fields": ["subtopic", "content", "display_name"],
    },
    "basic_problem": {
        "description": "Easy problem on prerequisite concept",
        "fields": ["problem_id", "title", "source", "reason"],
    },
    "retry": {
        "description": "Retry the original problem",
        "fields": ["problem_id", "reason"],
    },
    "video_link": {
        "description": "Link to video explanation (future)",
        "fields": ["url", "title", "duration"],
    },
}

ERROR_TYPE_TO_REMEDIATION = {
    "concept": {
        "description": "Conceptual misunderstanding",
        "approach": "Review underlying concept, then practice basics",
        "requires_mini_lesson": True,
    },
    "algebra": {
        "description": "Algebraic/computational error",
        "approach": "Practice similar computations",
        "requires_mini_lesson": False,
    },
    "logic": {
        "description": "Logical reasoning error",
        "approach": "Review problem structure, practice similar setup",
        "requires_mini_lesson": True,
    },
    "careless": {
        "description": "Careless mistake",
        "approach": "Retry same problem with careful checking",
        "requires_mini_lesson": False,
    },
}
